### ISSUE TITLE
Not working with private Repositories

### ISSUE THREAD

**Issue by abhijithnraj** [jerry1100/github-markdown-printer#1]
This is a fine tool. But it doesn't do anything for private repo. Can someone do something about this.

**Comment by jerry1100** [comment]
@abhijithnraj thanks for reporting. I'll take a look

**Comment by jerry1100** [comment]
I can't seem to reproduce it on my end. Could you provide more info?

1. Is your repo hosted on GitHub?
2. Is the GMP icon enabled? (not grayed out)

**Comment by jerry1100** [comment]
Yes, I just tried it on a private repo and it works fine.

Can you answer my questions above?

**Comment by jerry1100** [comment]
@abhijithnraj just checking up, are you still experiencing issues?

**Comment by jerry1100** [comment]
@abhijithnraj I'm gonna close this due to inactivity. Feel free to reopen it if the issue comes back.
