### ISSUE TITLE
Broken with Github's redesign

### ISSUE THREAD

**Issue by FlyOrBoom** [jerry1100/github-markdown-printer#10]
The design refresh introduced a pretty nice printer-friendly version, but I would still love for this to be updated so I can print only the markdown portion of the page.

![image](https://user-images.githubusercontent.com/31298876/85506181-b722da00-b5a4-11ea-9617-bd274da43473.png)

**Comment by jerry1100** [comment]
I was hoping the redesign wouldn’t break it. :/

Thanks for reporting, I’ll take a look this weekend.

**Comment by jerry1100** [comment]
Actually, it seems to still be working for me. What OS are you running?

![image](https://user-images.githubusercontent.com/18181641/85515620-09f69480-b599-11ea-8dd3-bd84c705cc65.png)

![image](https://user-images.githubusercontent.com/18181641/85515587-0105c300-b599-11ea-8fa1-4c8515337ed5.png)

**Comment by FlyOrBoom** [comment]
Reproduced on both Chrome OS 83.0.4103.112 64-bit and Ubuntu LTS 20.04 Chromium 83.0.4103.106 64-bit

**Comment by FlyOrBoom** [comment]
![image](https://user-images.githubusercontent.com/31298876/85572309-b9f3ee00-b5e9-11ea-8a78-51357ee24a4c.png)

**Comment by FlyOrBoom** [comment]
Nevermind. I think it's the other extensions I've installed on Chrome OS. Clicking the icon doesn't trigger a print prompt there. The extension on Chromium is formatting fine.

**Comment by jerry1100** [comment]
Sorry, does that mean this is not actually a bug, and can be closed?

**Comment by FlyOrBoom** [comment]
I believe so. Unfortunately the Chromebook is school-administered, so I can't test with the extensions disabled.
