### ISSUE TITLE
GMP icon unresponsive when clicked.

### ISSUE THREAD

**Issue by deborahtrez** [jerry1100/github-markdown-printer#13]
I installed the extension on Chrome. and opened the markdown file on github. When i click the icon, nothing happens!
This is the file I am trying to print.
https://github.com/deborahtrez/Outreachy_contract/blob/master/intern-contract-Aanyu%20Deborah%20Oduman-2020-11-25%20(2).md

Why is not working?

**Comment by jerry1100** [comment]
Hey @deborahtrez, it's working for me.
<img width="1575" alt="Screen Shot 2021-01-02 at 1 48 22 PM" src="https://user-images.githubusercontent.com/18181641/103468804-31c17480-4d01-11eb-8182-1e1eb43813fc.png">

Does the extension have read & write permissions? It should be able to read & write from all sites (github.com is fine too).
<img width="664" alt="Screen Shot 2021-01-02 at 1 49 07 PM" src="https://user-images.githubusercontent.com/18181641/103468814-50277000-4d01-11eb-8634-c84756a73b84.png">

**Comment by deborahtrez** [comment]
Oh. It's working *now* 😄 
Thank you Jerry.

**Comment by tnguyen14** [comment]
I'm running into the same problem, and I do have the permissions set to "On All Sites". I've tried this on chrome browser on 2 different machines.

**Comment by tnguyen14** [comment]
Looks like the fix is to go to "Manage Extensions", and turn on "Allow access to File URLs".
