### ISSUE TITLE
Greyed Out / Unresponsive

### ISSUE THREAD

**Issue by mikeconti** [jerry1100/github-markdown-printer#15]
First, let me say I love your github-markdown-printer extension ~ I use it all of the time so thanks for that!

Recently, the extension is greyed out in my extensions menu. When I go to the manage extension view and toggle `Allow in incognito` and `Allow access to file URLs`, it becomes un-greyed but is still unresponsive. I also have the extension allowed `On all sites`.

I've uninstalled and reinstalled the extensions a few times and am running Ver 0.7.

Thanks so much!

-- M

Edit: Played around with a few things and it looks like it's working totally fine on public repos but not private
Edit#02: Now it's working fine!? Thanks!

<img width="312" alt="fig1" src="https://user-images.githubusercontent.com/46979702/123318211-f9a32d80-d4fc-11eb-863a-a550889d2b20.png">

<img width="718" alt="fig2" src="https://user-images.githubusercontent.com/46979702/123318233-fe67e180-d4fc-11eb-880b-4d7cf6d2df71.png">

**Comment by jerry1100** [comment]
Haha, glad you find it useful :)
