### ISSUE TITLE
Right-click context menu entry

### ISSUE THREAD

**Issue by martin-braun** [jerry1100/github-markdown-printer#19]
I would love if this extension also appears in the right-click menu when I right-click anywhere on GitHub. The reason is simply, I can make space in my extension pin bar on the top right. Every pixel counts since I often use the browser in smaller windows due to window management. 

It's cumbersome to either find this extension in a huge extension list (when not pinning it) or inspecting URLs in a way-to-short address bar.

Thanks in advance. :)

**Comment by jerry1100** [comment]
Hey @martin-braun, this is a great idea. I just published v0.9 which includes this context menu.

![image](https://user-images.githubusercontent.com/18181641/163243994-2bd6c59e-4527-41b3-8d6f-d8e60d6ecb0f.png)

I'm going to make this the recommended way of triggering this extension. Sorry it took so long :)
