### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by deadcoder0904** [jerry1100/github-markdown-printer#20]
Love this extension but I love Github's Dark Mode. Can you add support for that?

**Comment by jerry1100** [comment]
I appreciate dark mode as well, but for PDFs, light is the way to go. It _could_ be configurable, but I don't want to introduce extra complexity that I don't feel is worth it.

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/18181641/163115754-1f67a6ae-7301-47fe-bf33-55aeffdf8f45.png">

Appreciate the comment though.
