### ISSUE TITLE
Support embedded Mermaid Diagrams

### ISSUE THREAD

**Issue by Structed** [jerry1100/github-markdown-printer#21]
GitHub recently introduced embedded Mermaid Diagram rendering. It would be fantastic, if these could be in the print output as well.

Currently, a diagram I embedded has just it's frame and the "expand" button rendered:

![image](https://user-images.githubusercontent.com/29922/157057325-c0abd36f-8edf-4670-887d-93bed1e61bf0.png)

The expand button, should ideally not get printed.

**Comment by jerry1100** [comment]
Wow, that's cool. I didn't know about mermaid diagrams.

I just released v0.10 with support for rendering mermaid diagrams.

![image](https://user-images.githubusercontent.com/18181641/163696839-3cf00020-8eed-44be-88c6-7bd4e1ca5c36.png)

Unfortunately, there are issues rendering iframes in print layouts, so it can be a bit flaky for certain diagrams. However, it should work in most cases. If you find a diagram that doesn't work, open a new issue and I'll have a look.
