### ISSUE TITLE
Support printing GitHub issue in full, not just the 1st post

### ISSUE THREAD

**Issue by John-foobar-Doe** [jerry1100/github-markdown-printer#22]
For example, when navigating to https://github.com/jerry1100/github-markdown-printer/issues/9, right-clicking to select "Print GitHub Markdown" (or clicking its chrome extension icon) will only show and print the 1st post/comment, but not any further or later comments. So is it possible to make this able to show and print an entire issue with all comments? Many thanks!

**Comment by jerry1100** [comment]
Printing GitHub issues aren't supported, and I don't think they should be.

Even if we wanted to, it's not a simple thing to support, since _each_ comment has its own markdown content.

If you really want to print issues, I recommend just using the default browser printer (ctrl+p or cmd+p).
