### ISSUE TITLE
When the markdown has diagrams, extension doesn't wait until the diagrams be rendered

### ISSUE THREAD

**Issue by leoboles** [jerry1100/github-markdown-printer#23]
Open a page with 5 or 6 mermaid diagrams and ask to print.

Part of the diagrams will not be rendered because extension doesn't wait enough time to render them.

**Comment by jerry1100** [comment]
Yea, I couldn't figure out a reliable way to wait for diagrams to load. Right now there's a fixed 1.5s delay which I found was long enough for two medium-sized diagrams or so.

I don't have time to look into this again, but one thing I could try doing is scaling the delay proportional to the amount of diagrams there are.

**Comment by jerry1100** [comment]
Feel free to give it a crack

**Comment by spydmobile** [comment]
wow this is too bad, I use mermaid all the time :( I think until you find a sweet spot, you should consider setting the daely to a sensible default (1.5 sec) and exposing it as an option in the UI so that when we come upon a diagram heavy markdown, we can adjust print and move on.

**Comment by jerry1100** [comment]
Do you mind listing down some mermaid diagram links I can use to test against? The more the better. Also if you could group them by size that would be helpful.

**Comment by spydmobile** [comment]
Well here is one: This one has 5 small but complicated git charts, it fails to render and print using GMP.
https://github.com/WISE-Developers/Project_issues/blob/main/geneology.md

**Comment by jerry1100** [comment]
It's been a while but I figured out a way to somewhat reliably wait until the diagrams render.

Check it out in v0.11 from the chrome web store.
