### ISSUE TITLE
Rendering of colors broken

### ISSUE THREAD

**Issue by blaumeise20** [jerry1100/github-markdown-printer#24]
GitHub uses color variables which are defined in elements that are normally parents of the .markdown-body element. If you try to print it, it replaces the body contents with only that element, removing all variables. So the headers have no border and code blocks are not highlighted etc. Is there a way to fix this?

**Comment by jerry1100** [comment]
Could you be more specific? A link to a repro would be helpful.

I see code block are not shaded but I'm not sure what you mean by headers not having borders.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/18181641/229379769-289ea446-cf8b-4809-ac6b-e40308574ff7.png">

**Comment by blaumeise20** [comment]
Weird, it doesn't work for me:
<img width="576" alt="Bildschirmfoto 2023-04-03 um 06 53 35" src="https://user-images.githubusercontent.com/62756994/229414800-247af9ef-37cd-4d9b-ba91-1957576acd6b.png">
Also links are not colored, just every kind of style element is missing. I'm using Chrome 111 on MacOS 12.6.1, if that helps you. I have also enabled background graphics in the print dialog just as said in the tutorial.

**Comment by jerry1100** [comment]
I see. I'll take a look this weekend or next.

**Comment by SMenigat** [comment]
I think it could be [this problem documented here](https://github.com/jerry1100/github-markdown-printer/issues/27#issuecomment-1555755218). @blaumeise20 are you using the GitHub default light theme or one of the dark theme variants?

**Comment by blaumeise20** [comment]
I use dark theme and it does indeed work when I switch to light theme.

I will close this in favour of https://github.com/jerry1100/github-markdown-printer/issues/27#issuecomment-1555755218.
