### ISSUE TITLE
Links not enabled

### ISSUE THREAD

**Issue by dineshbvadhia** [jerry1100/github-markdown-printer#25]
Should links in the markdown be enabled in the pdf?

**Comment by jerry1100** [comment]
Yes they should. Are they not working for you?

I just tried and they're still working for me.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/18181641/231012900-6576b747-2f8e-439e-8943-e3e716717095.png">

**Comment by jerry1100** [comment]
Closing since I haven't heard back. Feel free to reopen if this is still happening and include some more information like:
1. Your OS (windows/mac)
2. Your browser (chrome/safari/edge)
3. A link
