### ISSUE TITLE
GitHub Styles not applied to Markdown

### ISSUE THREAD

**Issue by SMenigat** [jerry1100/github-markdown-printer#27]
Hi Jerry,
thank you for that very useful extension 🥇 

While trying it out earlier I found that the GitHub styles were not properly applied to the rendered markdown. 
For example `h3`'s would not have that nice horizontal line below them, links would not be colored, inline code blocks have no background and so on. 

Maybe this short video helps in understanding what I mean:

https://user-images.githubusercontent.com/7868768/235305767-906e7e1c-1a7c-4a9e-be5a-28b93b4d82f6.mov

**Comment by jerry1100** [comment]
Thanks for the video. I've been busy but I'll see if I can take a look this weekend.

**Comment by jerry1100** [comment]
Had some time to look but unfortunately couldn't repro. Had some questions though:
1. Does this happen in Chrome? Wondering if it's an edge-specific issue.
2. I noticed your color scheme is different than the default, do you by chance have any custom CSS applied to the page from say another extension?

**Comment by SMenigat** [comment]
Hi Jerry, good morning 👋🏻 ☕ 

1. Yes this also happens in Chrome (I guess in all chromium based browsers)
2. No I don't use custom styles. This is the GitHub dark mode setting that can be configured through their settings. And this ended up to be the problem. The extension only works for the "default light" Theme and seems to break for the others. Maybe this could be added to the README to make it clear to future users of this very useful extension. 

Thanks again for your time on working on this 🏅

**Comment by jerry1100** [comment]
Thanks for the info. I was able to repro and push out a fix in v0.11. It's currently live on the Chrome web store, Edge usually takes a week.
