### ISSUE TITLE
Nothing happens when I click the GMP button

### ISSUE THREAD

**Issue by jackcrane** [jerry1100/github-markdown-printer#3]
When I am in a GH wiki and i click on the GMP icon in the URL/extension tray, it just pops up the options as though I had right-clicked it.

Any tips?

**Comment by jerry1100** [comment]
Thanks for reporting. I actually hadn't enabled it for wiki pages, but I spent some time on it tonight and actually got it working without too much effort.

I published v0.5 which supports wiki pages. Give that a try :).

**Comment by jackcrane** [comment]
Thanks so much!
