### ISSUE TITLE
Loosing data when trying to print preview when doing inline editing on github

### ISSUE THREAD

**Issue by hlevring** [jerry1100/github-markdown-printer#32]
It does work to print preview when doing inline editing.
https://cloud.videocom.com/media/fi_01J96XQ0PSBQK62ZVCTC3Q6AA6

1. Edit a readme.md file on github inline
2. Goto github markdown preview
3. Right click the preview page to open your extensions PDF print preview (checking that things looks right)
4. Exit PDF print preview
5. You have now lost your inline readme.md edits

**Comment by jerry1100** [comment]
Hey, just want to understand the problem better. The link you shared seems to be just an image - a video would be helpful.

Is the problem that activating the markdown printer while your editing markdown, will cause you to lose your edits? If so, there's unfortunately not much we can do about that, but perhaps you could try saving your markdown before triggering the printer.

**Comment by hlevring** [comment]
>Is the problem that activating the markdown printer while your editing markdown, will cause you to lose your edits?
Yes correct.

>but perhaps you could try saving your markdown before triggering the printer.
Yes that is the issue. I would make my inline edits, use the github markdown preview and from there use the PDF printer but if doing that the edits gets lost  - hmm A way to work around this would be to just be to open a new tab, so your edits remain intact in the first tab.

Anyways its not really a big issue, and possible to work around so will close the issue if its nothing you can do something about from your end
