### ISSUE TITLE
Feature request: get the html file instead of printing it

### ISSUE THREAD

**Issue by imambungo** [jerry1100/github-markdown-printer#4]
Having an option to get the Html file would be great.

**Comment by jerry1100** [comment]
I feel that this is a pretty niche scenario so unless there's visible demand, I don't want to overcomplicate the functionality.

However, it is possible and fairly easy to do.

### Step 1 - Navigate to the page you want to print
Any page with a markdown preview will work (including wikis). Issue and pull request threads won't work.

### Step 2 - Open your devtools and paste this in the console
This applies the [exact styles](https://github.com/jerry1100/github-markdown-printer/blob/master/src/style.css) as GMP when it prepares the page for printing, with the only exception being the padding here to create some page margins.
```javascript
const style = document.createElement('style');

style.innerHTML = `
  div.position-relative {
    position: static !important;
  }

  body * {
    visibility: hidden !important;
    position: static !important;
  }

  #wiki-body > .markdown-body,
  article.markdown-body.entry-content {
    position: absolute !important;
    top: 0 !important;
    left: 0 !important;
    padding: 50px !important; // adjust as needed
    border: none !important;
  }

  #wiki-body > .markdown-body *,
  article.markdown-body.entry-content * {
    visibility: visible !important;
  }

  #wiki-body > .markdown-body pre,
  article.markdown-body.entry-content pre {
    white-space: pre-wrap !important;
  }
`;

document.head.appendChild(style);
```

### Step 3 - When you're ready to print, paste this into your devtools' console
This actually downloads the html. Credit goes to [Louis on StackOverflow](https://stackoverflow.com/a/26690558).
```javascript
        var file = new window.Blob([document.documentElement.innerHTML], { type: "text/html" });
        var URL = window.webkitURL || window.URL;

        // This is the URL that will download the data.
        var downloadUrl = URL.createObjectURL(file);

        var a = document.createElement("a");
        // This sets the file name.
        a.download = "source.htm";
        a.href = downloadUrl;

        // Actually perform the download.
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
```

**Comment by imambungo** [comment]
Okay, no problem. Thank you for giving the workaround :+1:
