### ISSUE TITLE
Can you allow it to print gists?

### ISSUE THREAD

**Issue by endrebak** [jerry1100/github-markdown-printer#5]
gist.github.com :)

**Comment by jerry1100** [comment]
It already does print markdown gists :). Give this a try: https://gist.github.com/lava/f8732a6802988fe8d0a41bd7979a4d54.

**Comment by endrebak** [comment]
Ah, I wanted to print code really. It can print markdown, but not code. I was thinking that it could print all nice github pages, not just markdown :)
