### ISSUE TITLE
Should work in Edge Chromium

### ISSUE THREAD

**Issue by AlanChurchill** [jerry1100/github-markdown-printer#6]
Microsoft Edge Chromium uses the Chrome engine. This does not work in Edge (printer pop-up does not appear). Suggest supporting both and putting this in the Microsoft store as well. Normally, Chrome extensions work fine in Edge Chromium but this did not. Not sure why but FYI.

**Comment by jerry1100** [comment]
Thanks for posting. I'll take a look when I have some time.

**Comment by jerry1100** [comment]
Hey @AlanChurchill, sorry for the late response.

It works fine for me on Edge Chromium (installed via Chrome Web Store). Can you please try again?
![image](https://user-images.githubusercontent.com/18181641/86080600-fe8ae980-ba2e-11ea-8051-e59ec5bba5d0.png)

As for putting it on the Microsoft store, I'll create another issue so this one doesn't

**Comment by jerry1100** [comment]
As for publishing it on the Microsoft store, I opened https://github.com/jerry1100/github-markdown-printer/issues/11 as to not drag this issue out.

**Comment by AlanChurchill** [comment]
Thanks Jerry for looking at this. Edge has had numerous updates since I first tried it. The print dialogue now appears to open fine so it may have been an Edge update. I don't have a need to print markdown often but nice to have  tool to do it.

Thanks for creating open source tools. Very helpful that the community does things like this for developers, like me, who rely on people's generosity with their time.
