### ISSUE TITLE
Rendering text with emphasis does not work.

### ISSUE THREAD

**Issue by covejstewart** [jerry1100/github-markdown-printer#9]
Chrome Version 81.0.4044.138 (Official Build) (64-bit)
GMP Version 0.5

Render test markdown: https://gist.github.com/covejstewart/41dea674578b355317252ecb2f442694

Output:
![render_md_pdf__1_page_](https://user-images.githubusercontent.com/139935/82022426-82387480-9641-11ea-9c7b-2e72ebac1ea6.png)

PDF:
[render.md.pdf](https://github.com/jerry1100/github-markdown-printer/files/4632809/render.md.pdf)

**Comment by jerry1100** [comment]
Hmm, it works fine when I try it
![image](https://user-images.githubusercontent.com/18181641/82024702-e0f2f380-962b-11ea-8cc3-5c3933339f91.png)

What OS are you using? It looks like it italicized characters are affected.

**Comment by covejstewart** [comment]
macOS Catalina (10.15.4)

**Comment by covejstewart** [comment]
This looks like it may be a known issue in Chrome on macOS Catalina: https://bugs.chromium.org/p/chromium/issues/detail?id=1018581

**Comment by jerry1100** [comment]
Interesting. Thanks for finding the chromium bug report.

I also have a Mac so I’ll take a look tomorrow.

**Comment by jerry1100** [comment]
Able to repro in macOS Catalina 10.15.4, Chrome 81.0.4044.138.

<img width="1699" alt="Screen Shot 2020-05-15 at 9 09 38 AM" src="https://user-images.githubusercontent.com/18181641/82087486-112aa880-96a5-11ea-94bc-29e2526fa227.png">

I guess let's just wait for it to be fixed in Chromium. Thanks for reporting.

**Comment by jerry1100** [comment]
Seems like [it's been fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1018581). Can you try again?

**Comment by jerry1100** [comment]
Hey @covejstewart, I'm gonna close this since it should be fixed.

If it's not, feel free to reopen.
